apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pwmanager
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - backend
              topologyKey: kubernetes.io/hostname
      serviceAccountName: backend-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: wait-for-postgres
          image: busybox@sha256:6b219909078e3fc93b81f83cb438bd7a5457984a01a478c76fe9777a8c67c39e
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
        - name: migrate
          image: ghcr.io/dom2701/pwmanager_securitybydesign/backend@sha256:693bbc72f3bf9b4ee5d961cf74c1de7efb366c7ad0ed900bee144f25444ee096
          imagePullPolicy: Always
          command: ["/app/migrate", "up"]
          envFrom:
            - configMapRef:
                name: pwmanager-config
          env:
            - name: DATABASE_URL_FILE
              value: /etc/secrets/DATABASE_URL
            - name: REDIS_URL_FILE
              value: /etc/secrets/REDIS_URL
            - name: SESSION_SECRET_FILE
              value: /etc/secrets/SESSION_SECRET
            - name: MASTER_ENCRYPTION_KEY_FILE
              value: /etc/secrets/MASTER_ENCRYPTION_KEY
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: secrets-mount
              mountPath: /etc/secrets
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      containers:
        - name: backend
          image: ghcr.io/dom2701/pwmanager_securitybydesign/backend@sha256:693bbc72f3bf9b4ee5d961cf74c1de7efb366c7ad0ed900bee144f25444ee096
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: pwmanager-config
          env:
            - name: DATABASE_URL_FILE
              value: /etc/secrets/DATABASE_URL
            - name: REDIS_URL_FILE
              value: /etc/secrets/REDIS_URL
            - name: SESSION_SECRET_FILE
              value: /etc/secrets/SESSION_SECRET
            - name: MASTER_ENCRYPTION_KEY_FILE
              value: /etc/secrets/MASTER_ENCRYPTION_KEY
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /home/appuser/.cache
            - name: secrets-mount
              mountPath: /etc/secrets
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: secrets-mount
          secret:
            secretName: pwmanager-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pwmanager
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pwmanager
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - frontend
              topologyKey: kubernetes.io/hostname
      serviceAccountName: frontend-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: ghcr.io/dom2701/pwmanager_securitybydesign/frontend@sha256:4fb6e73eda69ed0c05a0db557f3fd052f6e4141f2d9ea9006ebf464508963ddb
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pwmanager
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
